project_id = "trfjldpqwzcuvfxxbkqs"

[functions.contact-notify]
verify_jwt = false

[functions.ai-article-generator]
verify_jwt = true

[functions.auth-signup-notify]
verify_jwt = false

[functions.generate-weekly-poll]
verify_jwt = true
