// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trfjldpqwzcuvfxxbkqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyZmpsZHBxd3pjdXZmeHhia3FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODUxNTksImV4cCI6MjA3MjY2MTE1OX0.NWvguaSXaPCjZa0W_KQHris0aMgtGBxM8TU0zvx6B_Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});